### ISSUE TITLE
Does "playsinline" work well?

### ISSUE THREAD

**Issue by kyungtaek** [Chris-Perkins/TwitchPlayer#2]
Hi Chris!

First, Thanks because I got a hint from your source.
I have a question, Does "playsinline" option work well?

I tried both your source and my source, but I failed to prevent to launch default full-screen player of iOS. Do you have any tip or solution about it?

Thank you :)

**Comment by Chris-Perkins** [comment]
Hi kyungtaek! I am currently away from my development computer, but I will try to help remotely. I believe you can disable all full-screen behavior by setting the "allows full screen" property to false. It also looks like there's a stack overflow issue that might help located [here](https://stackoverflow.com/questions/51160244/disabling-auto-play-in-full-screen-on-ios).

Let me know if any of these resolve your issue. Otherwise, I will have my dev environment back up in a few days and can look for myself :)
